name: Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Inject keys
        run: |
          echo -en '${{ secrets.KEYS_INI }}' >> keys.ini

      - name: Test with pytest
        run: |
          pip install pytest
          python -m pytest
